---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cideorgc/sebastian/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp upload.php $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R carpeta_archivo $DEPLOYPATH